name: CheckPackage
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          max-parallel: 5
          matrix:
            python-version: ["3.7", "3.8", "3.9", "3.10"]
        steps:
            - uses: actions/checkout@v3
            - name: Install poetry
              run: pipx install poetry
            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
                #cache: 'poetry'
            # - name: Install dependencies
            #   run: |
            #     python -m pip install --upgrade pip setuptools wheel build_utils
            # - name: Lint with flake8
            #   run: |
            #     pip install flake8
            #     # stop the build if there are Python syntax errors or undefined names
            #     flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
            #     # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
            #     flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
            - name: Turn off Virtualenvs
              run: poetry config virtualenvs.create false
            - name: Install packages
              run: poetry install
            - name: Run PyTest
              run: poetry run pytest
            # - name: Run mypy
            #   run: poetry run mypy pyservos
            # - name: nosetests
            #   run: |
            #     pip install nose
            #     cd python
            #     python -m pip install -e .
            #     cd tests
            #     nosetests -vs test.py
            # - name: Python Style Checker
            #   uses: andymckay/pycodestyle-action@0.1.3
